- MobileCRM/MobileCRM.Shared/Pages/LoginPage.cs
Encourage best practices by default, yo!
(Released under APACHE2; no attribution required)
> visually obscure password input

- Todo/PCL/Todo.WinPhone/SQLite_WinPhone.cs
Removed the usage of a non-declared variable.
> [Todo] Fixed compilation error for Windows Phone.

- CustomRenderers/ContentPage/CustomRenderer.WinPhone81/CameraPageRenderer.cs
Sample "CustomRenderers/ContentPage" Fixed (Bug 37027)
> Sample "CustomRenderers/ContentPage" Fixed (Bug 37027)

- FormsGallery/FormsGallery/FormsGallery/ImageCellDemoPage.cs
- FormsGallery/FormsGallery/FormsGallery/ImageDemoPage.cs
Sample Fixed "FormsGallery". Bug#42201
> Sample Fixed "FormsGallery". Bug#42201

- WorkingWithMaps/WorkingWithMaps/MapAppPage.cs
Bug: https://bugzilla.xamarin.com/show_bug.cgi?id=43418
> Added target platform for Windows Phone

- Todo/PCL/Todo.iOS/AppDelegate.cs
- Todo/PCL/Todo.iOS/Todo.iOS.csproj
- Todo/PCL/Todo.iOS/packages.config
- Todo/PCL/Todo/App.cs
- Todo/PCL/Todo/Todo.csproj
- Todo/PCL/Todo/packages.config
Added references and codes for mobile center integration
> Added references and codes for mobile center integration

- Todo/PCL/Todo.iOS/AppDelegate.cs
- Todo/PCL/Todo.iOS/Todo.iOS.csproj
- Todo/PCL/Todo.iOS/packages.config
- Todo/PCL/Todo/App.cs
- Todo/PCL/Todo/Todo.csproj
- Todo/PCL/Todo/packages.config
Reverts xamarin/xamarin-forms-samples#155
> Revert "Added references and codes for mobile center integration"

- EmployeeDirectory/EmployeeDirectory.Android/Resources/Resource.designer.cs
- EmployeeDirectory/EmployeeDirectory.iOS/EmployeeDirectory.iOS.csproj
- EmployeeDirectory/EmployeeDirectory.iOS/packages.config
The EmployeeDirectory had the following issues which are resolved in this PR:
- It was using Components which are now obsolete
- Build errors
I've fixed those and tested in iOS and Android emulator. There are a couple build warnings but we can circle back to fix those later.
> Updating EmployeeDirectory sample

- Navigation/TabbedPageWithNavigationPage/Droid/Resources/Resource.designer.cs
- Navigation/TabbedPageWithNavigationPage/Droid/Resources/values/styles.xml
- Navigation/TabbedPageWithNavigationPage/Droid/TabbedPageWithNavigationPage.Droid.csproj
- Navigation/TabbedPageWithNavigationPage/TabbedPageWithNavigationPage.sln
Fixes: https://github.com/xamarin/xamarin-android/issues/1800
Upon launching the app, I was getting the following error on startup:
Unhandled Exception:
Android.Content.Res.Resources+NotFoundException: Resource ID #0x0 occurred
The following changes got it working again:
- Set SLN to deploy (setting for VS Windows)
- Updated `styles.xml` with what the latest project template has
- Changed NuGet versions of Android Support Libraries
> Fixes for TabbedPageWithNavigationPage on Android

- CustomRenderers/Map/Circle/Droid/MapOverlay.Droid.csproj
- CustomRenderers/Map/Pin/Droid/CustomRenderer.Droid.csproj
- CustomRenderers/Map/Polygon/Droid/MapOverlay.Droid.csproj
- CustomRenderers/Map/Polyline/Droid/MapOverlay.Droid.csproj
- FormsGallery/FormsGallery/FormsGallery.Android/FormsGallery.Android.csproj
- MobileCRM/MobileCRM.Android/MobileCRM.Android.csproj
- WebServices/TodoAzurePush/Droid/Services/FirebaseNotificationService.cs
- WebServices/TodoAzurePush/Droid/TodoAzure.Droid.csproj
- WorkingWithMaps/Android/WorkingWithMaps.Android.csproj
These Android projects will currently fail on computers which have a recent fresh install of Xamarin. These old GooglePlayServices package references result produce the following build error if the Xamarin Build Download Cache is not already in place with the relevant .aar files.
```
(_XamarinBuildDownloadPartialZipsCore target) -> 
/Users/foo/.nuget/packages/xamarin.build.download/0.4.7/build/Xamarin.Build.Download.targets(62,3): error XBD009: Partial Download Failed for one or more parts [/Users/foo/xamarin-forms-samples/CustomRenderers/Map/Pin/Droid/CustomRenderer.Droid.csproj]
/Users/foo/.nuget/packages/xamarin.build.download/0.4.7/build/Xamarin.Build.Download.targets(62,3): error : Invalid 'HttpContent' instance provided. It does not have a content type header starting with …
```
> Bump some projects to Xamarin.GooglePlayServices 11.4.2

- UsingUITest/README.md
Fixed spelling of "AutomationId" in readme.md
> Fixed "AutomationId" spelling

- TipCalc/TipCalc/TipCalc.iOS/AppDelegate.cs
> cleaning up AppDelegate.cs

- Advanced/DependencyResolution/DIContainerDemo/README.md
Just updated link documentation. The current link just goes to 404 Not Found.
No code or nuget change.
> Corrected link

- Pages/DataPagesDemo/Droid/DataPagesDemo.Droid.csproj
- WebServices/OAuthNativeFlow/Droid/OAuthNativeFlow.Droid.csproj
- WebServices/TodoAzureAuthADB2CClientFlow/Droid/TodoAzure.Droid.csproj
- WebServices/TodoDocumentDBAuth/Xamarin.Forms/Droid/TodoDocumentDB.Droid.csproj
Problem:
> NU1107: Version conflict detected for Xamarin.Android.Support.Compat)
Fixed by following nuget suggestion:
> Install/reference Xamarin.Android.Support.Compat 27.0.2.1 directly to project OAuthNativeFlow.Droid to resolve this issue
Restore log:
$ nuget restore
NuGet Version: 4.8.1.5435
MSBuild auto-detection: using msbuild version '15.0' from '/Library/Frameworks/Mono.framework/Versions/5.20.0/lib/mono/msbuild/15.0/bin'. Use option -MSBuildVersion to force nuget to use a specific version of MSBuild.
MSBuild P2P timeout [ms]: 120000
/Library/Frameworks/Mono.framework/Versions/Current/Commands/msbuild "/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/NuGetScratch/9o5dgdho.5ab.nugetinputs.targets" /t:GenerateRestoreGraphFile /nologo /nr:false /v:q …
> Fix nuget restore problem.

- WebServices/TodoWCF/README.md
> WCF sample readme updates

- UsingUITest/UsingUITest.UITests/AppInitializer.cs
- UsingUITest/UsingUITest.UITests/Tests.cs
- UsingUITest/UsingUITest.UITests/UsingUITest.UITests.csproj
> Fixing #405, #475 on UsingUITest solution

- WebServices/AzureADB2CAuth/ADB2CAuthorization/ADB2CAuthorization.csproj
- WebServices/AzureADB2CAuth/ADB2CAuthorization/App.xaml.cs
- WebServices/AzureADB2CAuth/ADB2CAuthorization/Constants.cs
- WebServices/AzureADB2CAuth/ADB2CAuthorization/LoginPage.xaml.cs
- WebServices/AzureADB2CAuth/Droid/ADB2CAuthorization.Droid.csproj
- WebServices/AzureADB2CAuth/Droid/MainActivity.cs
- WebServices/AzureADB2CAuth/UWP/ADB2CAuthorization.UWP.csproj
- WebServices/AzureADB2CAuth/iOS/ADB2CAuthorization.iOS.csproj
- WebServices/AzureADB2CAuth/iOS/AppDelegate.cs
Shortly after this sample was last updated there were two major MSAL version updates that both introduced breaking changes. NuGet packages have been updated to MSAL 4.0 and all breaking changes addressed in this PR.
> Jusjohns MSAL v4 update

- README.md
Update README for new code sample browser on docs.microsoft.com
> [yaml] instructions for new metadata format

- WebServices/AzureADB2CAuth/Droid/Properties/AndroidManifest.xml
Minor fix to bad quotes in the android manifest
> Fixed bad quotes in manifest

- UserInterface/ContentViewDemos/CardViewDemo/CardViewDemo/Controls/CardView.xaml
Added fallbacks to custom `ContentView` so that it shows something in the XAML previewer.
Fixes https://github.com/MicrosoftDocs/xamarin-docs/issues/2333
> ContentView fallback values

- FormsGallery/FormsGallery/FormsGallery.Android/MainActivity.cs
- FormsGallery/FormsGallery/FormsGallery.iOS/AppDelegate.cs
- FormsGallery/FormsGallery/FormsGallery/CodeExamples/IndicatorViewDemoPage.cs
- FormsGallery/FormsGallery/FormsGallery/CodeExamplesMainPage.cs
- FormsGallery/FormsGallery/FormsGallery/HomePage.xaml
- FormsGallery/FormsGallery/FormsGallery/XamlExamples/IndicatorViewDemoPage.xaml
- FormsGallery/FormsGallery/FormsGallery/XamlExamples/IndicatorViewDemoPage.xaml.cs
- UserInterface/CarouselViewDemos/CarouselViewDemos.Android/MainActivity.cs
- UserInterface/CarouselViewDemos/CarouselViewDemos.iOS/AppDelegate.cs
- UserInterface/IndicatorViewDemos/IndicatorViewDemos.Android/MainActivity.cs
- UserInterface/IndicatorViewDemos/IndicatorViewDemos.iOS/AppDelegate.cs
- UserInterface/LayoutCompression/Droid/MainActivity.cs
- UserInterface/LayoutCompression/Droid/Properties/AndroidManifest.xml
- UserInterface/Xaminals/Xaminals.Android/MainActivity.cs
- UserInterface/Xaminals/Xaminals.iOS/AppDelegate.cs
Corrected usage of `SetFlags` API throughout the repo.
> SetFlags updates.

- GetStarted/Tutorials/ListViewTutorial/ListViewTutorial/MainPage.xaml.cs
Changes all images to load via https to compliment the fix in the docs
https://github.com/MicrosoftDocs/xamarin-docs/issues/2750
> Changes all images to load via https to compliment the fix in the docs https://github.com/MicrosoftDocs/xamarin-docs/issues/2750

- WebServices/TodoDocumentDBAuth/ResourceTokenBroker/ResourceTokenBroker/ResourceTokenBroker.csproj
- WebServices/TodoDocumentDBAuth/ResourceTokenBroker/ResourceTokenBroker/packages.config
Fixes https://github.com/xamarin/xamarin-forms-samples/issues/571
> Fix ResourceTokenBroker

- DataBindingDemos/DataBindingDemos/DataBindingDemos.Android/DataBindingDemos.Android.csproj
- DataBindingDemos/DataBindingDemos/DataBindingDemos.UWP/DataBindingDemos.UWP.csproj
- DataBindingDemos/DataBindingDemos/DataBindingDemos.iOS/DataBindingDemos.iOS.csproj
- DataBindingDemos/DataBindingDemos/DataBindingDemos/App.xaml.cs
- DataBindingDemos/DataBindingDemos/DataBindingDemos/DataBindingDemos.csproj
- UserInterface/ExpanderDemos/ExpanderDemos.Android/ExpanderDemos.Android.csproj
- UserInterface/ExpanderDemos/ExpanderDemos.iOS/ExpanderDemos.iOS.csproj
- UserInterface/ExpanderDemos/ExpanderDemos/ExpanderDemos.csproj
- UserInterface/MediaElementDemos/MediaElementDemos.Android/MediaElementDemos.Android.csproj
- UserInterface/MediaElementDemos/MediaElementDemos.iOS/MediaElementDemos.iOS.csproj
- UserInterface/MediaElementDemos/MediaElementDemos/MediaElementDemos.csproj
> Update XCT to v1.0.0

- WebServices/TodoREST/iOS/TodoREST.iOS.csproj
> make hot restart ready

- WebServices/TodoREST/TodoAPI/TodoAPI/Program.cs
- WebServices/TodoREST/TodoAPI/TodoAPI/Startup.cs
- WebServices/TodoREST/TodoAPI/TodoAPI/TodoAPI.csproj
> minor fix to code for Create backend services for native mobile apps with ASP.NET Core

- LocalNotifications/LocalNotifications/LocalNotifications.Android/AlarmHandler.cs
- LocalNotifications/LocalNotifications/LocalNotifications.Android/AndroidNotificationManager.cs
- LocalNotifications/LocalNotifications/LocalNotifications.Android/BootReceiver.cs
- LocalNotifications/LocalNotifications/LocalNotifications.Android/LocalNotifications.Android.csproj
- LocalNotifications/LocalNotifications/LocalNotifications.Android/Properties/AndroidManifest.xml
- LocalNotifications/LocalNotifications/LocalNotifications.iOS/AppDelegate.cs
- LocalNotifications/LocalNotifications/LocalNotifications.iOS/iOSNotificationReceiver.cs
Update the local notifications sample to include the ability to process notifications when the app is backgrounded or killed.
> Backgrounded app updates.

- WebServices/TodoREST/TodoAPI/TodoAPI/Controllers/TodoItemsController.cs
- WebServices/TodoREST/TodoAPI/TodoAPI/Startup.cs
Snippets easier and more robust code reference .
> Add #region snippet to Web API code

- WebServices/TodoREST/Droid/TodoREST.Android.csproj
- WebServices/TodoREST/TodoAPI/TodoAPI/Properties/launchSettings.json
- WebServices/TodoREST/TodoREST/Data/RestService.cs
- WebServices/TodoREST/TodoREST/Models/TodoItem.cs
- WebServices/TodoREST/TodoREST/TodoREST.csproj
- WebServices/TodoREST/iOS/TodoREST.iOS.csproj
Replaced Newtonsoft.Json with System.Text.Json. Fixes #706
> Use System.Text.Json

- UserInterface/WebView/WebViewSample/WebViewSample/Code Implementation/LinkToInAppCode.cs
- UserInterface/WebView/WebViewSample/WebViewSample/Code Implementation/LoadingLabelCode.cs
- UserInterface/WebView/WebViewSample/WebViewSample/XAML Implementation/LinkToInAppXaml.xaml.cs
- UserInterface/WebView/WebViewSample/WebViewSample/XAML Implementation/LoadingLabelXaml.xaml
- WorkingWithWebview/WorkingWithWebview/WebAppPage.cs
Updated the URLs in the WebView samples from HTTP to HTTPS.
> WebView samples - URL updates

- SignInWithApple/README.md
Corrects typo in docs.
Scope of changes is restricted to docs only.
- [ x] Rebased on top of master at time of the pull request.
- [ x] Changes adhere to coding standard in the sample.
> fix(docs): corrects typo in project documentation
