Forms2Native/Forms2Native.Android/Forms2Native.Android.csproj
Forms2Native/Forms2Native.Android/MainActivity.cs
Forms2Native/Forms2Native.WinPhone/MainPage.xaml.cs
Forms2Native/Forms2Native.iOS/AppDelegate.cs
Forms2Native/Forms2Native/App.cs
Forms2Native/Forms2Native/Forms2Native.csproj
Forms2Native/Forms2Native/MyFirstPage.cs
Forms2Native/Forms2Native/NativeNavigationArgs.cs

Android needs to use StartActivity without a custom renderer to make the back navigation work properly.
With the current implementation on Android you go to the third page, and then when you press back you end up on a blank third page. You have to press back again to go back to the first page.
A better approach is to use MessageCenter to allow each platform to decide how to do the navigation. I chose to make iOS and Windows to the same thing that was done before. On Android instead of pushing a page on the navigation stack it just calls StartActivity (directly from MainActivity), which allows the back button to do the right thing.
I have seen multiple people get confused about this on the forums. This is a much better example of how to do this.

Use MessagingCenter to allow each platform to control how the navigation happens

---

Native2Forms/Native2Forms.Android/MainActivity.cs

This avoids an ambiguous reference between 'Xamarin.Forms.Platform.Android.Resource' and 'Native2Forms.Android.Resource' that will occur when Forms is upgraded to 2.1. 
See https://bugzilla.xamarin.com/show_bug.cgi?id=38313

Avoiding ambiguous reference that will occur after upgrade to Forms 2.1

---

Todo/PCL/Todo.iOS/Todo.iOS.csproj

Reference to that resource was already being inherited from parent. For some reason it wasn't an issue in Xamarin Studio for MAC but was throwing an error in Visual Studio for Windows. After the change, it works in both platforms.
It is a fix for the bug [https://bugzilla.xamarin.com/show_bug.cgi?id=45068](https://bugzilla.xamarin.com/show_bug.cgi?id=45068)

Removed unnecessary SQLitePCL.raw reference in iOS Project

---

Native2Forms/Native2Forms.Android/MainActivity.cs

The current Native2Forms Android example is using `FormsApplicationActivity` as the starting point for the Android example; it should be using a `Activity`.

Use a native Android activity in the Native2Forms example

---

WorkingWithFiles/PCL/WorkingWithFiles/LoadResourceJson.cs
WorkingWithFiles/PCL/WorkingWithFiles/LoadResourceText.cs
WorkingWithFiles/PCL/WorkingWithFiles/LoadResourceXml.cs

GetInfo is now called specifically from InstrospectionExtensions, avoiding ambiguity with other reflection extensions (e.g., TypeExtensions GetInfo).

Ambiguity in System.Reflection GetInfo()

---

WebServices/AzureSearch/MonkeyApp/Constants.cs

Looks like the Azure.Search now checks the URLs for invalid
characters. Changing the `Constants` strings make it start at least. I
guess the crash at the sample start is not intended.
Fixes #559641

[MonkeyApp] Change Constants so that the sample doesn't crash on startup

---

CustomRenderers/ContentPage/iOS/CameraPageRenderer.cs
CustomRenderers/ContentPage/iOS/Info.plist

- fixed crush when capturing (info.plist)
- fixed [bugzilla bug](https://github.com/xamarin/xamarin-forms-samples/commits/master) - additional disposing
- fixed screen size - not it depends on `View.Bounds.Width`
- updated obsolete `DefaultDeviceWithMediaType` method

[XI] fixed crush when capturing, "CustomRenderers" project

---

WebServices/TodoASMX/UWP/SoapService.cs

https://github.com/xamarin/xamarin-forms-samples/tree/master/WebServices/TodoASMX
The UWP project wasn't changing the endpoint based on the value of 
```c#
Constants.SoapUrl
```

Added code to set the UWP endpoint to the value of Constants.SoapUrl

---

WebServices/TodoCognitiveServices/iOS/Info.plist

https://github.com/xamarin/xamarin-forms-samples/tree/master/WebServices/TodoCognitiveServices
NSMicrophoneUsageDescription has to be set to something otherwise app crashes when trying to record

NSMicrophoneUsageDescription required otherwise app crashes

---

WebServices/OAuthNativeFlow/iOS/Entitlements.plist

Updated `keychain-access-groups` value because the installation into the real device was failed. 
```
Installing application bundle 'com.xamarin.oauthnativeflow' on '{device-name}'
ApplicationVerificationFailed: Failed to verify code signature of /private/var/installd/Library/Caches/com.apple.mobile.installd.staging/temp.aTf4Q6/extracted/OAuthNativeFlow.iOS.app : 0xe8008016 (The executable was signed with invalid entitlements.)
error MT1006: Could not install the application '..../xamarin-forms-samples/WebServices/OAuthNativeFlow/iOS/bin/iPhone/Debug/OAuthNativeFlow.iOS.app' on the device '{device-name}': Your code signing/provisioning profiles are not correctly configured. Probably you have an entitlement not supported by your current provisioning profile, or your device is not part of …
```

[XI] fixed `keychain-access-groups` value; "OAuthNativeFlow.iOS" project

---

CustomRenderers/View/iOS/CustomRenderer.iOS.csproj

Fixed:
```
MTOUCH : error MT0116: Invalid architecture: i386. 32-bit architectures are not supported when deployment target is 11 or later.
```

[CustomRenderer] Fixed 'MtouchArch' in 'Release' configuration

---

XamlSamples/XamlSamples/XamlSamples/HslColorScrollPage.xaml
XamlSamples/XamlSamples/XamlSamples/SliderBindingsPage.xaml
XamlSamples/XamlSamples/XamlSamples/SliderTransformsPage.xaml
XamlSamples/XamlSamples/XamlSamples/XamlPlusCodePage.xaml

Add padding to sliders, to prevent the UINavigationController 'back' gesture being triggered.
Fixes https://github.com/MicrosoftDocs/xamarin-docs/issues/962
- [n/a] Consolidated NuGet packages across all projects in the sample (when changing existing package versions).

docs issue 962 - fix sliders

---

WebServices/TodoREST/iOS/TodoREST.iOS.csproj

This fixes a build problem where the iOS project isn't passed the reference to
the referenced .NET Standard project's nuget reference, and the linker ends up
complaining that it can't find the NuGet:
MTOUCH : error MT2001: Could not link assemblies. Reason: Error while processing references of 'TodoRESTiOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' [/xamarin-forms-samples/WebServices/TodoREST/iOS/TodoREST.iOS.csproj]
--- inner exception (TaskId:143)
Mono.Linker.LoadException: Error while processing references of 'TodoRESTiOS, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null' ---> Mono.Cecil.AssemblyResolutionException: Failed to resolve assembly: 'Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' ---> …

Make TodoRest.iOS a PackageRef project.

---

WebServices/AzureNotificationHub/NotificationHubSample/NotificationHubSample.Android/NotificationHubSample.Android.csproj
WebServices/AzureNotificationHub/NotificationHubSample/NotificationHubSample.Android/Properties/AndroidManifest.xml

Context: https://developer.android.com/about/versions/marshmallow/android-6.0-changes#behavior-apache-http-client
If you build the project with `<AndroidDexTool>d8</AndroidDexTool>`, you will hit:
R8 : warning : Missing class: org.apache.http.client.methods.HttpEntityEnclosingRequestBase
R8 : error : Compilation can't be completed because some library classes are missing.
There is a missing `<uses-library/>` element that is needed since Android 6.0.
I also removed the multi-dex setting, since this project does not appear to need it.

[NotificationHubSample] fix for using D8

---

WebServices/AzureADB2CAuth/ADB2CAuthorization/ADB2CAuthorization.csproj
WebServices/AzureADB2CAuth/ADB2CAuthorization/App.xaml.cs
WebServices/AzureADB2CAuth/Droid/ADB2CAuthorization.Droid.csproj
WebServices/AzureADB2CAuth/UWP/ADB2CAuthorization.UWP.csproj
WebServices/AzureADB2CAuth/iOS/ADB2CAuthorization.iOS.csproj

This PR fixes a bug with our ADB2C sample where authentication doesn't work _if_ your azure configuration has multiple Redirect URIs defined. It also updates MSAL version to latest at the time of this PR.
Mentioned in: https://github.com/Azure-Samples/active-directory-b2c-xamarin-native/issues/28
Mentioned in: https://github.com/MicrosoftDocs/xamarin-docs/issues/2326
Fixes https://github.com/xamarin/xamarin-forms-samples/issues/555

jusjohns ADB2C fixes

---

WebServices/AzureSignalR/ChatClient.UWP/ChatClient.UWP.csproj
WebServices/AzureSignalR/ChatClient/ChatClient.csproj
WebServices/AzureSignalR/ChatClient/SignalRService.cs

This PR fixes an issue with the Xam Forms + SignalR sample. A change in the default JSON serialization protocol caused communication to break. You must specify that newtonsoft JSON be used for compatibility.
See: https://github.com/MicrosoftDocs/xamarin-docs/issues/2419

Jusjohns SignalR sample fix

---

SkiaSharpForms/Demos/Demos/SkiaSharpFormsDemos/Curves/PathExtensions.cs

Fixes a bug in code related to SkiaSharp.  The flattened points of a conic curve were calculated but not added to the returned set of points.  Compare with the similar code in the other cases to help see that this line was missing.
P.S.
This flattening code is fantastic!  It is a shame that it only exists in a demo.
- I made no change to package versions.
- I adapted this code in another project and tested there in WPF.  I didn't test on any other platforms.  I doubt such testing is needed.

Create and add the flattened conic segments to returned path

---

WebServices/AzureSignalR/ChatClient/ChatClient.csproj

Context: https://github.com/xamarin/xamarin-forms-samples/pull/573
The version of `Microsoft.AspNetCore.SignalR.Client` used by SignalR was
recently updated. Both the `Microsoft.AspNetCore.SignalR.Client` and
`Microsoft.Extensions.Logging.Console` packages have a dependency on
`Microsoft.Extensions.Logging`. We should make sure to keep the
version of that shared dependency in sync.
This fixes an issue that would occur when building the SignalR Android
project with the linker enabled:
/Library/Frameworks/Mono.framework/External/xbuild/Xamarin/Android/Xamarin.Android.Common.targets(1947,5): error XALNK7000: Mono.Linker.MarkException: Error processing method: 'System.IDisposable Microsoft.Extensions.Logging.Console.ConsoleLogger::BeginScope(TState)' in assembly: …

Update Microsoft.Extensions.Logging.Console version in SignalR

---

CustomRenderers/View/iOS/UICameraPreview.cs

Draw is only called once and is not called if the layout of the view changes.
We had an issue logged here
https://github.com/xamarin/Xamarin.Forms/issues/9623
But you can manifest the same issue by changing the orientation on the device.
- Launch camera sample in portrait
- rotate to landscape
You will notice that without this change the preview window doesn't resize

Update PreviewLayer in LayoutSubviews not Draw

---

FormsGallery/FormsGallery/FormsGallery.Android/MainActivity.cs
FormsGallery/FormsGallery/FormsGallery.UWP/App.xaml.cs
FormsGallery/FormsGallery/FormsGallery.iOS/AppDelegate.cs
FormsGallery/FormsGallery/FormsGallery/CodeExamples/EllipseDemoPage.cs
FormsGallery/FormsGallery/FormsGallery/CodeExamples/LineDemoPage.cs
FormsGallery/FormsGallery/FormsGallery/CodeExamples/PathDemoPage.cs
FormsGallery/FormsGallery/FormsGallery/CodeExamples/PolygonDemoPage.cs
FormsGallery/FormsGallery/FormsGallery/CodeExamples/PolylineDemoPage.cs
FormsGallery/FormsGallery/FormsGallery/CodeExamples/RectangleDemoPage.cs
FormsGallery/FormsGallery/FormsGallery/CodeExamplesMainPage.cs
FormsGallery/FormsGallery/FormsGallery/HomePage.xaml
FormsGallery/FormsGallery/FormsGallery/XamlExamples/EllipseDemoPage.xaml
FormsGallery/FormsGallery/FormsGallery/XamlExamples/EllipseDemoPage.xaml.cs
FormsGallery/FormsGallery/FormsGallery/XamlExamples/LineDemoPage.xaml
FormsGallery/FormsGallery/FormsGallery/XamlExamples/LineDemoPage.xaml.cs
FormsGallery/FormsGallery/FormsGallery/XamlExamples/PathDemoPage.xaml
FormsGallery/FormsGallery/FormsGallery/XamlExamples/PathDemoPage.xaml.cs
FormsGallery/FormsGallery/FormsGallery/XamlExamples/PolygonDemoPage.xaml
FormsGallery/FormsGallery/FormsGallery/XamlExamples/PolygonDemoPage.xaml.cs
FormsGallery/FormsGallery/FormsGallery/XamlExamples/PolylineDemoPage.xaml
FormsGallery/FormsGallery/FormsGallery/XamlExamples/PolylineDemoPage.xaml.cs
FormsGallery/FormsGallery/FormsGallery/XamlExamples/RectangleDemoPage.xaml
FormsGallery/FormsGallery/FormsGallery/XamlExamples/RectangleDemoPage.xaml.cs

Added Shapes to FormsGallery

---

Behaviors/EventToCommandBehavior/EventToCommandBehavior/Behaviors/EventToCommandBehavior.cs

This allows behaviors to be attached to page events via <ContentPage.Behaviors> like Appearing and Disappearing. Without this fix, we get the cryptic following error:
"Additional information: bindable not an instance of AssociatedType"
Original discussion and solution here:
https://forums.xamarin.com/discussion/comment/230200/#Comment_230200

Fix issue with Content Page behaviors

---

LocalNotifications/LocalNotifications/LocalNotifications.Android/AlarmHandler.cs
LocalNotifications/LocalNotifications/LocalNotifications.Android/AndroidNotificationManager.cs
LocalNotifications/LocalNotifications/LocalNotifications.Android/LocalNotifications.Android.csproj
LocalNotifications/LocalNotifications/LocalNotifications.Android/MainActivity.cs
LocalNotifications/LocalNotifications/LocalNotifications.Android/Properties/AndroidManifest.xml
LocalNotifications/LocalNotifications/LocalNotifications.iOS/iOSNotificationManager.cs
LocalNotifications/LocalNotifications/LocalNotifications/App.xaml.cs
LocalNotifications/LocalNotifications/LocalNotifications/INotificationManager.cs
LocalNotifications/LocalNotifications/LocalNotifications/MainPage.xaml
LocalNotifications/LocalNotifications/LocalNotifications/MainPage.xaml.cs

Added scheduled notifications example to the local notifications sample.

Add scheduled notifications example

---

BoxView/DotMatrixClock/DotMatrixClock/DotMatrixClock/MainPage.xaml

Small change to update the dotmatrix clock sample to use safearea, ensuring the clock does not get lost under the notch in landscape mode.

Updating DotMatrix clock to use iOS SafeArea
